# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Per Diem App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Per Diem App
pod "Floaty", "~> 4.0.0"
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'CalendarDateRangePickerViewController'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'AAPickerView'
pod 'FormValidatorSwift'
pod 'PDTSimpleCalendar'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod 'ImagePicker'
pod 'Firebase/Core'
pod 'Firebase/MLVision'


  target 'Per Diem AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Per Diem AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
